dashboard:
  image: kadirahq/meteord
  ports:
   - "80:80"
  links:
   - mongo
  environment:
   - MONGO_URL=mongodb://mongo/meteor-db
   - ROOT_URL=http://[your domain]
   - BUNDLE_URL=https://cdn.rawgit.com/openteach/release/master/releases/[release].tar.gz

mongo:
  image: mongo:latest